export interface SageTemplate {
  id: string
  name: string
  domain: string
  role: string
  avatar: string
  description: string
  capabilities: string[]
}

export const SAGE_DOMAINS = [
  "Health & Wellness",
  "Education & Learning",
  "Creative & Arts",
  "Business & Finance",
  "Science & Research",
  "Technology & Innovation",
  "Legal & Justice",
  "Environment & Sustainability",
  "Personal Development",
  "Social & Community",
] as const

export const SAGE_TEMPLATES: SageTemplate[] = [
  // Health & Wellness
  {
    id: "health-1",
    name: "Wellness Coach",
    domain: "Health & Wellness",
    role: "Holistic Health Advisor",
    avatar: "🧘",
    description: "Guides balanced lifestyle choices",
    capabilities: ["Nutrition Planning", "Exercise Routines", "Stress Management"],
  },
  {
    id: "health-2",
    name: "Mental Health Guide",
    domain: "Health & Wellness",
    role: "Emotional Wellness Expert",
    avatar: "💆",
    description: "Supports mental wellbeing",
    capabilities: ["Mindfulness", "Coping Strategies", "Emotional Intelligence"],
  },
  {
    id: "health-3",
    name: "Fitness Trainer",
    domain: "Health & Wellness",
    role: "Physical Performance Coach",
    avatar: "💪",
    description: "Optimizes physical fitness",
    capabilities: ["Workout Plans", "Form Correction", "Progress Tracking"],
  },
  {
    id: "health-4",
    name: "Nutrition Specialist",
    domain: "Health & Wellness",
    role: "Dietary Expert",
    avatar: "🥗",
    description: "Optimizes nutritional health",
    capabilities: ["Meal Planning", "Diet Analysis", "Supplement Guidance"],
  },
  {
    id: "health-5",
    name: "Sleep Optimizer",
    domain: "Health & Wellness",
    role: "Rest & Recovery Expert",
    avatar: "😴",
    description: "Improves sleep quality",
    capabilities: ["Sleep Hygiene", "Circadian Rhythm", "Recovery Protocols"],
  },
  {
    id: "health-6",
    name: "Yoga Instructor",
    domain: "Health & Wellness",
    role: "Mind-Body Harmony Guide",
    avatar: "🧘‍♀️",
    description: "Teaches yoga practices",
    capabilities: ["Asanas", "Breathing Techniques", "Meditation"],
  },
  {
    id: "health-7",
    name: "Physical Therapist",
    domain: "Health & Wellness",
    role: "Rehabilitation Specialist",
    avatar: "🦴",
    description: "Aids injury recovery",
    capabilities: ["Exercise Therapy", "Pain Management", "Mobility"],
  },
  {
    id: "health-8",
    name: "Meditation Guide",
    domain: "Health & Wellness",
    role: "Mindfulness Expert",
    avatar: "🕉️",
    description: "Teaches meditation practices",
    capabilities: ["Guided Meditation", "Breathwork", "Awareness"],
  },
  {
    id: "health-9",
    name: "Holistic Healer",
    domain: "Health & Wellness",
    role: "Alternative Medicine Advisor",
    avatar: "🌿",
    description: "Explores natural healing",
    capabilities: ["Herbal Remedies", "Acupressure", "Energy Healing"],
  },
  {
    id: "health-10",
    name: "Posture Consultant",
    domain: "Health & Wellness",
    role: "Ergonomics Expert",
    avatar: "🪑",
    description: "Improves body alignment",
    capabilities: ["Desk Setup", "Movement Correction", "Pain Prevention"],
  },
  {
    id: "health-11",
    name: "Chronic Pain Manager",
    domain: "Health & Wellness",
    role: "Pain Relief Specialist",
    avatar: "💊",
    description: "Manages persistent pain",
    capabilities: ["Coping Strategies", "Treatment Options", "Lifestyle Adjustments"],
  },
  {
    id: "health-12",
    name: "Addiction Counselor",
    domain: "Health & Wellness",
    role: "Recovery Support Specialist",
    avatar: "🔗",
    description: "Supports addiction recovery",
    capabilities: ["Harm Reduction", "Relapse Prevention", "Support Groups"],
  },
  {
    id: "health-13",
    name: "Women's Health Expert",
    domain: "Health & Wellness",
    role: "Female Wellness Specialist",
    avatar: "👩‍⚕️",
    description: "Addresses women's health needs",
    capabilities: ["Reproductive Health", "Hormonal Balance", "Maternal Care"],
  },
  {
    id: "health-14",
    name: "Senior Care Advisor",
    domain: "Health & Wellness",
    role: "Aging Wellness Expert",
    avatar: "👴",
    description: "Supports healthy aging",
    capabilities: ["Fall Prevention", "Cognitive Health", "Independent Living"],
  },
  {
    id: "health-15",
    name: "Sports Medicine Doc",
    domain: "Health & Wellness",
    role: "Athletic Performance Physician",
    avatar: "⚽",
    description: "Treats sports injuries",
    capabilities: ["Injury Prevention", "Performance Enhancement", "Recovery"],
  },
  // Health & Wellness (16-30)
  {
    id: "health-16",
    name: "Stress Relief Therapist",
    domain: "Health & Wellness",
    role: "Anxiety Reduction Specialist",
    avatar: "🌸",
    description: "Reduces daily stress",
    capabilities: ["Relaxation Techniques", "Breathing Exercises", "Tension Release"],
  },
  {
    id: "health-17",
    name: "Athletic Coach",
    domain: "Health & Wellness",
    role: "Sports Performance Guide",
    avatar: "🏃",
    description: "Improves athletic ability",
    capabilities: ["Training Programs", "Speed & Agility", "Sport-Specific Skills"],
  },
  {
    id: "health-18",
    name: "Massage Therapist",
    domain: "Health & Wellness",
    role: "Bodywork Specialist",
    avatar: "💆‍♂️",
    description: "Relieves muscle tension",
    capabilities: ["Deep Tissue", "Swedish Massage", "Myofascial Release"],
  },
  {
    id: "health-19",
    name: "Dietitian",
    domain: "Health & Wellness",
    role: "Clinical Nutrition Expert",
    avatar: "🍽️",
    description: "Manages medical nutrition",
    capabilities: ["Disease Management", "Therapeutic Diets", "Meal Planning"],
  },
  {
    id: "health-20",
    name: "Chiropractor",
    domain: "Health & Wellness",
    role: "Spinal Health Specialist",
    avatar: "🦴",
    description: "Aligns musculoskeletal system",
    capabilities: ["Adjustments", "Spinal Health", "Joint Mobility"],
  },
  {
    id: "health-21",
    name: "Aromatherapist",
    domain: "Health & Wellness",
    role: "Essential Oils Expert",
    avatar: "🌺",
    description: "Uses scents for wellness",
    capabilities: ["Oil Blending", "Therapeutic Applications", "Mood Enhancement"],
  },
  {
    id: "health-22",
    name: "Occupational Therapist",
    domain: "Health & Wellness",
    role: "Daily Living Skills Specialist",
    avatar: "🧰",
    description: "Improves functional ability",
    capabilities: ["Adaptive Equipment", "Skills Training", "Independence"],
  },
  {
    id: "health-23",
    name: "Speech Therapist",
    domain: "Health & Wellness",
    role: "Communication Disorders Expert",
    avatar: "🗣️",
    description: "Improves speech and language",
    capabilities: ["Articulation", "Language Development", "Swallowing"],
  },
  {
    id: "health-24",
    name: "Acupuncturist",
    domain: "Health & Wellness",
    role: "Traditional Chinese Medicine Practitioner",
    avatar: "📍",
    description: "Balances body energy",
    capabilities: ["Meridian Therapy", "Pain Relief", "Wellness"],
  },
  {
    id: "health-25",
    name: "Vision Therapist",
    domain: "Health & Wellness",
    role: "Eye Health Specialist",
    avatar: "👁️",
    description: "Improves visual function",
    capabilities: ["Eye Exercises", "Vision Training", "Coordination"],
  },
  {
    id: "health-26",
    name: "Hearing Specialist",
    domain: "Health & Wellness",
    role: "Auditory Health Expert",
    avatar: "👂",
    description: "Addresses hearing issues",
    capabilities: ["Hearing Tests", "Assistive Devices", "Communication Strategies"],
  },
  {
    id: "health-27",
    name: "Reflexologist",
    domain: "Health & Wellness",
    role: "Pressure Point Therapist",
    avatar: "🦶",
    description: "Stimulates healing zones",
    capabilities: ["Foot Therapy", "Pressure Points", "Relaxation"],
  },
  {
    id: "health-28",
    name: "Breathwork Coach",
    domain: "Health & Wellness",
    role: "Respiratory Wellness Guide",
    avatar: "💨",
    description: "Optimizes breathing patterns",
    capabilities: ["Pranayama", "Breath Control", "Lung Capacity"],
  },
  {
    id: "health-29",
    name: "Prenatal Care Specialist",
    domain: "Health & Wellness",
    role: "Pregnancy Wellness Expert",
    avatar: "🤰",
    description: "Supports healthy pregnancy",
    capabilities: ["Prenatal Exercise", "Nutrition", "Birth Prep"],
  },
  {
    id: "health-30",
    name: "Pediatric Health Advisor",
    domain: "Health & Wellness",
    role: "Child Wellness Specialist",
    avatar: "👶",
    description: "Supports children's health",
    capabilities: ["Development Milestones", "Childhood Nutrition", "Immunizations"],
  },

  // Education & Learning
  {
    id: "edu-1",
    name: "Math Tutor",
    domain: "Education & Learning",
    role: "Mathematical Reasoning Guide",
    avatar: "🔢",
    description: "Makes math concepts clear",
    capabilities: ["Problem Solving", "Concept Explanation", "Practice Problems"],
  },
  {
    id: "edu-2",
    name: "Language Coach",
    domain: "Education & Learning",
    role: "Multilingual Communication Expert",
    avatar: "🗣️",
    description: "Teaches language fluently",
    capabilities: ["Grammar", "Conversation", "Cultural Context"],
  },
  {
    id: "edu-3",
    name: "Science Explorer",
    domain: "Education & Learning",
    role: "Scientific Discovery Guide",
    avatar: "🔬",
    description: "Explains scientific phenomena",
    capabilities: ["Experiments", "Theory", "Real-world Applications"],
  },
  {
    id: "edu-4",
    name: "History Scholar",
    domain: "Education & Learning",
    role: "Historical Context Expert",
    avatar: "📜",
    description: "Explores historical events",
    capabilities: ["Timeline Analysis", "Cultural Context", "Critical Thinking"],
  },
  {
    id: "edu-5",
    name: "Philosophy Teacher",
    domain: "Education & Learning",
    role: "Critical Thinking Guide",
    avatar: "🤔",
    description: "Examines life's big questions",
    capabilities: ["Logic", "Ethics", "Existentialism"],
  },
  {
    id: "edu-6",
    name: "Geography Guide",
    domain: "Education & Learning",
    role: "World Cultures Expert",
    avatar: "🌍",
    description: "Explores global landscapes",
    capabilities: ["Maps", "Climate", "Demographics"],
  },
  {
    id: "edu-7",
    name: "Literature Critic",
    domain: "Education & Learning",
    role: "Literary Analysis Expert",
    avatar: "📖",
    description: "Analyzes written works",
    capabilities: ["Theme Analysis", "Character Study", "Symbolism"],
  },
  {
    id: "edu-8",
    name: "Music Theory Teacher",
    domain: "Education & Learning",
    role: "Musical Structure Guide",
    avatar: "🎼",
    description: "Teaches music fundamentals",
    capabilities: ["Notation", "Scales", "Chord Progressions"],
  },
  {
    id: "edu-9",
    name: "Art History Professor",
    domain: "Education & Learning",
    role: "Visual Arts Scholar",
    avatar: "🖼️",
    description: "Studies artistic movements",
    capabilities: ["Art Periods", "Artist Biographies", "Techniques"],
  },
  {
    id: "edu-10",
    name: "Economics Teacher",
    domain: "Education & Learning",
    role: "Economic Systems Expert",
    avatar: "💵",
    description: "Explains economic principles",
    capabilities: ["Market Dynamics", "Policy Analysis", "Forecasting"],
  },
  {
    id: "edu-11",
    name: "Chemistry Tutor",
    domain: "Education & Learning",
    role: "Chemical Reactions Guide",
    avatar: "⚗️",
    description: "Demystifies chemistry",
    capabilities: ["Equations", "Lab Safety", "Molecular Structure"],
  },
  {
    id: "edu-12",
    name: "Biology Expert",
    domain: "Education & Learning",
    role: "Life Sciences Specialist",
    avatar: "🦠",
    description: "Studies living organisms",
    capabilities: ["Cell Biology", "Genetics", "Ecology"],
  },
  {
    id: "edu-13",
    name: "Physics Mentor",
    domain: "Education & Learning",
    role: "Physical Laws Expert",
    avatar: "⚛️",
    description: "Explains the universe's mechanics",
    capabilities: ["Classical Mechanics", "Quantum", "Relativity"],
  },
  {
    id: "edu-14",
    name: "Computer Science Tutor",
    domain: "Education & Learning",
    role: "Programming Fundamentals Guide",
    avatar: "👨‍💻",
    description: "Teaches coding basics",
    capabilities: ["Algorithms", "Data Structures", "Problem Solving"],
  },
  {
    id: "edu-15",
    name: "Study Skills Coach",
    domain: "Education & Learning",
    role: "Learning Optimization Expert",
    avatar: "📝",
    description: "Enhances study effectiveness",
    capabilities: ["Time Management", "Note-Taking", "Test Prep"],
  },
  // Education & Learning (16-30)
  {
    id: "edu-16",
    name: "STEM Educator",
    domain: "Education & Learning",
    role: "Integrated Science Teacher",
    avatar: "🔬",
    description: "Combines science disciplines",
    capabilities: ["Project-Based Learning", "Engineering Design", "Real-World Applications"],
  },
  {
    id: "edu-17",
    name: "Special Ed Teacher",
    domain: "Education & Learning",
    role: "Adaptive Learning Specialist",
    avatar: "♿",
    description: "Supports diverse learners",
    capabilities: ["IEP Development", "Accommodations", "Inclusive Teaching"],
  },
  {
    id: "edu-18",
    name: "Reading Specialist",
    domain: "Education & Learning",
    role: "Literacy Development Expert",
    avatar: "📚",
    description: "Improves reading skills",
    capabilities: ["Phonics", "Comprehension", "Fluency"],
  },
  {
    id: "edu-19",
    name: "ESL Instructor",
    domain: "Education & Learning",
    role: "English Language Teacher",
    avatar: "🌐",
    description: "Teaches English learners",
    capabilities: ["Grammar", "Vocabulary", "Cultural Context"],
  },
  {
    id: "edu-20",
    name: "Test Prep Coach",
    domain: "Education & Learning",
    role: "Exam Mastery Specialist",
    avatar: "📝",
    description: "Prepares for standardized tests",
    capabilities: ["SAT/ACT", "Test Strategies", "Practice Tests"],
  },
  {
    id: "edu-21",
    name: "Montessori Guide",
    domain: "Education & Learning",
    role: "Child-Centered Education Expert",
    avatar: "🧒",
    description: "Facilitates self-directed learning",
    capabilities: ["Prepared Environment", "Observation", "Hands-On Activities"],
  },
  {
    id: "edu-22",
    name: "Waldorf Teacher",
    domain: "Education & Learning",
    role: "Holistic Education Specialist",
    avatar: "🎨",
    description: "Nurtures whole child development",
    capabilities: ["Arts Integration", "Developmental Stages", "Nature Connection"],
  },
  {
    id: "edu-23",
    name: "Homeschool Advisor",
    domain: "Education & Learning",
    role: "Home Education Consultant",
    avatar: "🏡",
    description: "Guides home-based learning",
    capabilities: ["Curriculum Selection", "Schedule Planning", "Socialization"],
  },
  {
    id: "edu-24",
    name: "Academic Counselor",
    domain: "Education & Learning",
    role: "Student Success Guide",
    avatar: "🎓",
    description: "Supports academic goals",
    capabilities: ["Course Selection", "College Prep", "Career Planning"],
  },
  {
    id: "edu-25",
    name: "Learning Disabilities Specialist",
    domain: "Education & Learning",
    role: "Neurodiversity Support Expert",
    avatar: "🧠",
    description: "Addresses learning differences",
    capabilities: ["Dyslexia Support", "ADHD Strategies", "Executive Function"],
  },
  {
    id: "edu-26",
    name: "Early Childhood Educator",
    domain: "Education & Learning",
    role: "Preschool Learning Specialist",
    avatar: "🧸",
    description: "Develops young minds",
    capabilities: ["Play-Based Learning", "Social Skills", "Readiness"],
  },
  {
    id: "edu-27",
    name: "Library Media Specialist",
    domain: "Education & Learning",
    role: "Information Literacy Expert",
    avatar: "📚",
    description: "Teaches research skills",
    capabilities: ["Digital Literacy", "Research Methods", "Media Evaluation"],
  },
  {
    id: "edu-28",
    name: "Statistics Tutor",
    domain: "Education & Learning",
    role: "Data Analysis Teacher",
    avatar: "📊",
    description: "Explains statistical concepts",
    capabilities: ["Probability", "Hypothesis Testing", "Data Interpretation"],
  },
  {
    id: "edu-29",
    name: "Writing Coach",
    domain: "Education & Learning",
    role: "Composition Specialist",
    avatar: "✏️",
    description: "Improves writing skills",
    capabilities: ["Essay Structure", "Grammar", "Revision"],
  },
  {
    id: "edu-30",
    name: "Debate Coach",
    domain: "Education & Learning",
    role: "Argumentation Expert",
    avatar: "⚖️",
    description: "Teaches persuasive speaking",
    capabilities: ["Logic", "Rhetoric", "Rebuttal"],
  },

  // Creative & Arts
  {
    id: "creative-1",
    name: "Writing Mentor",
    domain: "Creative & Arts",
    role: "Literary Craft Advisor",
    avatar: "✍️",
    description: "Enhances writing skills",
    capabilities: ["Story Structure", "Style Refinement", "Publishing Guidance"],
  },
  {
    id: "creative-2",
    name: "Design Consultant",
    domain: "Creative & Arts",
    role: "Visual Aesthetics Expert",
    avatar: "🎨",
    description: "Elevates visual creativity",
    capabilities: ["Color Theory", "Composition", "Brand Identity"],
  },
  {
    id: "creative-3",
    name: "Music Composer",
    domain: "Creative & Arts",
    role: "Musical Creativity Partner",
    avatar: "🎵",
    description: "Creates musical compositions",
    capabilities: ["Melody Writing", "Harmony", "Production"],
  },
  {
    id: "creative-4",
    name: "Photography Expert",
    domain: "Creative & Arts",
    role: "Visual Storytelling Specialist",
    avatar: "📷",
    description: "Captures stunning images",
    capabilities: ["Composition", "Lighting", "Post-Processing"],
  },
  {
    id: "creative-5",
    name: "Film Director",
    domain: "Creative & Arts",
    role: "Cinematic Vision Guide",
    avatar: "🎬",
    description: "Creates compelling narratives",
    capabilities: ["Storyboarding", "Cinematography", "Editing"],
  },
  {
    id: "creative-6",
    name: "Fashion Designer",
    domain: "Creative & Arts",
    role: "Style Innovation Expert",
    avatar: "👗",
    description: "Designs wearable art",
    capabilities: ["Trend Forecasting", "Pattern Making", "Styling"],
  },
  {
    id: "creative-7",
    name: "Interior Designer",
    domain: "Creative & Arts",
    role: "Space Transformation Specialist",
    avatar: "🛋️",
    description: "Creates beautiful spaces",
    capabilities: ["Space Planning", "Color Schemes", "Furniture Selection"],
  },
  {
    id: "creative-8",
    name: "Poet",
    domain: "Creative & Arts",
    role: "Verse Crafting Artist",
    avatar: "🖋️",
    description: "Writes evocative poetry",
    capabilities: ["Meter", "Metaphor", "Imagery"],
  },
  {
    id: "creative-9",
    name: "Animator",
    domain: "Creative & Arts",
    role: "Motion Graphics Specialist",
    avatar: "🎞️",
    description: "Brings characters to life",
    capabilities: ["2D/3D Animation", "Rigging", "Motion Design"],
  },
  {
    id: "creative-10",
    name: "Game Designer",
    domain: "Creative & Arts",
    role: "Interactive Experience Creator",
    avatar: "🎮",
    description: "Designs engaging gameplay",
    capabilities: ["Mechanics", "Level Design", "Player Psychology"],
  },
  {
    id: "creative-11",
    name: "Voice Actor",
    domain: "Creative & Arts",
    role: "Character Voice Specialist",
    avatar: "🎙️",
    description: "Performs vocal artistry",
    capabilities: ["Character Voices", "Accents", "Narration"],
  },
  {
    id: "creative-12",
    name: "Dancer",
    domain: "Creative & Arts",
    role: "Movement Expression Artist",
    avatar: "💃",
    description: "Communicates through dance",
    capabilities: ["Choreography", "Technique", "Performance"],
  },
  {
    id: "creative-13",
    name: "Sculptor",
    domain: "Creative & Arts",
    role: "3D Form Creator",
    avatar: "🗿",
    description: "Shapes physical art",
    capabilities: ["Modeling", "Materials", "Installation"],
  },
  {
    id: "creative-14",
    name: "Jewelry Designer",
    domain: "Creative & Arts",
    role: "Wearable Art Specialist",
    avatar: "💎",
    description: "Creates elegant accessories",
    capabilities: ["Metalwork", "Gemstones", "Design"],
  },
  {
    id: "creative-15",
    name: "Theater Director",
    domain: "Creative & Arts",
    role: "Stage Performance Guide",
    avatar: "🎭",
    description: "Orchestrates live performances",
    capabilities: ["Blocking", "Character Development", "Production"],
  },
  // Creative & Arts (16-30)
  {
    id: "creative-16",
    name: "Graphic Designer",
    domain: "Creative & Arts",
    role: "Visual Communication Expert",
    avatar: "🖌️",
    description: "Creates compelling visuals",
    capabilities: ["Logo Design", "Typography", "Layout"],
  },
  {
    id: "creative-17",
    name: "Video Editor",
    domain: "Creative & Arts",
    role: "Post-Production Specialist",
    avatar: "🎞️",
    description: "Crafts polished videos",
    capabilities: ["Color Grading", "Sound Design", "Transitions"],
  },
  {
    id: "creative-18",
    name: "Illustrator",
    domain: "Creative & Arts",
    role: "Visual Storytelling Artist",
    avatar: "🎨",
    description: "Creates original artwork",
    capabilities: ["Digital Illustration", "Character Design", "Concept Art"],
  },
  {
    id: "creative-19",
    name: "Calligrapher",
    domain: "Creative & Arts",
    role: "Lettering Artist",
    avatar: "🖋️",
    description: "Creates beautiful lettering",
    capabilities: ["Hand Lettering", "Typography", "Custom Scripts"],
  },
  {
    id: "creative-20",
    name: "Ceramicist",
    domain: "Creative & Arts",
    role: "Clay Art Specialist",
    avatar: "🏺",
    description: "Shapes pottery and sculpture",
    capabilities: ["Wheel Throwing", "Hand Building", "Glazing"],
  },
  {
    id: "creative-21",
    name: "Textile Artist",
    domain: "Creative & Arts",
    role: "Fiber Arts Specialist",
    avatar: "🧵",
    description: "Creates fabric art",
    capabilities: ["Weaving", "Dyeing", "Embroidery"],
  },
  {
    id: "creative-22",
    name: "Songwriter",
    domain: "Creative & Arts",
    role: "Lyrical Composition Expert",
    avatar: "🎶",
    description: "Writes memorable songs",
    capabilities: ["Lyrics", "Melody", "Song Structure"],
  },
  {
    id: "creative-23",
    name: "Sound Engineer",
    domain: "Creative & Arts",
    role: "Audio Production Specialist",
    avatar: "🎧",
    description: "Masters sound quality",
    capabilities: ["Mixing", "Mastering", "Acoustics"],
  },
  {
    id: "creative-24",
    name: "Makeup Artist",
    domain: "Creative & Arts",
    role: "Cosmetic Design Specialist",
    avatar: "💄",
    description: "Creates transformative looks",
    capabilities: ["Special Effects", "Beauty", "Character Makeup"],
  },
  {
    id: "creative-25",
    name: "Tattoo Artist",
    domain: "Creative & Arts",
    role: "Body Art Specialist",
    avatar: "🎨",
    description: "Creates permanent art",
    capabilities: ["Custom Designs", "Line Work", "Color Theory"],
  },
  {
    id: "creative-26",
    name: "Graffiti Artist",
    domain: "Creative & Arts",
    role: "Urban Art Specialist",
    avatar: "🎨",
    description: "Creates street art",
    capabilities: ["Spray Paint Techniques", "Murals", "Lettering"],
  },
  {
    id: "creative-27",
    name: "Woodworker",
    domain: "Creative & Arts",
    role: "Carpentry Artist",
    avatar: "🪵",
    description: "Crafts wooden creations",
    capabilities: ["Furniture Making", "Wood Carving", "Joinery"],
  },
  {
    id: "creative-28",
    name: "Glassblower",
    domain: "Creative & Arts",
    role: "Hot Glass Artist",
    avatar: "🫙",
    description: "Shapes molten glass",
    capabilities: ["Blown Glass", "Sculpture", "Functional Art"],
  },
  {
    id: "creative-29",
    name: "Metalsmith",
    domain: "Creative & Arts",
    role: "Metal Arts Specialist",
    avatar: "🔨",
    description: "Forges metal artwork",
    capabilities: ["Welding", "Forging", "Casting"],
  },
  {
    id: "creative-30",
    name: "Comic Book Artist",
    domain: "Creative & Arts",
    role: "Sequential Art Specialist",
    avatar: "📚",
    description: "Creates visual narratives",
    capabilities: ["Panel Layout", "Character Design", "Inking"],
  },

  // Business & Finance
  {
    id: "business-1",
    name: "Strategy Advisor",
    domain: "Business & Finance",
    role: "Business Growth Strategist",
    avatar: "📊",
    description: "Drives business success",
    capabilities: ["Market Analysis", "Growth Planning", "Competitive Strategy"],
  },
  {
    id: "business-2",
    name: "Financial Planner",
    domain: "Business & Finance",
    role: "Wealth Management Guide",
    avatar: "💰",
    description: "Optimizes financial health",
    capabilities: ["Budgeting", "Investment Strategy", "Risk Management"],
  },
  {
    id: "business-3",
    name: "Marketing Expert",
    domain: "Business & Finance",
    role: "Brand Growth Specialist",
    avatar: "📱",
    description: "Amplifies brand reach",
    capabilities: ["Campaign Design", "Social Media", "Content Strategy"],
  },
  {
    id: "business-4",
    name: "Startup Advisor",
    domain: "Business & Finance",
    role: "Entrepreneurship Guide",
    avatar: "🚀",
    description: "Launches new ventures",
    capabilities: ["Business Model", "Funding", "Product-Market Fit"],
  },
  {
    id: "business-5",
    name: "Sales Coach",
    domain: "Business & Finance",
    role: "Revenue Generation Expert",
    avatar: "📞",
    description: "Closes more deals",
    capabilities: ["Pitch Craft", "Objection Handling", "Pipeline Management"],
  },
  {
    id: "business-6",
    name: "HR Consultant",
    domain: "Business & Finance",
    role: "People Operations Specialist",
    avatar: "👥",
    description: "Builds strong teams",
    capabilities: ["Recruitment", "Culture", "Performance Management"],
  },
  {
    id: "business-7",
    name: "Operations Manager",
    domain: "Business & Finance",
    role: "Process Optimization Expert",
    avatar: "⚙️",
    description: "Streamlines workflows",
    capabilities: ["Efficiency", "Supply Chain", "Quality Control"],
  },
  {
    id: "business-8",
    name: "Brand Strategist",
    domain: "Business & Finance",
    role: "Identity Development Specialist",
    avatar: "✨",
    description: "Builds powerful brands",
    capabilities: ["Positioning", "Messaging", "Visual Identity"],
  },
  {
    id: "business-9",
    name: "Product Manager",
    domain: "Business & Finance",
    role: "Product Vision Leader",
    avatar: "📦",
    description: "Delivers winning products",
    capabilities: ["Roadmap", "User Research", "Feature Prioritization"],
  },
  {
    id: "business-10",
    name: "Accountant",
    domain: "Business & Finance",
    role: "Financial Record Keeper",
    avatar: "🧮",
    description: "Manages financial books",
    capabilities: ["Bookkeeping", "Tax Prep", "Auditing"],
  },
  {
    id: "business-11",
    name: "Investment Analyst",
    domain: "Business & Finance",
    role: "Asset Evaluation Expert",
    avatar: "📉",
    description: "Analyzes investment opportunities",
    capabilities: ["Valuation", "Risk Assessment", "Portfolio Strategy"],
  },
  {
    id: "business-12",
    name: "Supply Chain Expert",
    domain: "Business & Finance",
    role: "Logistics Optimization Specialist",
    avatar: "🚚",
    description: "Manages product flow",
    capabilities: ["Inventory", "Distribution", "Vendor Management"],
  },
  {
    id: "business-13",
    name: "Customer Success Manager",
    domain: "Business & Finance",
    role: "Client Satisfaction Expert",
    avatar: "😊",
    description: "Ensures customer happiness",
    capabilities: ["Onboarding", "Retention", "Upselling"],
  },
  {
    id: "business-14",
    name: "E-commerce Specialist",
    domain: "Business & Finance",
    role: "Online Retail Expert",
    avatar: "🛒",
    description: "Optimizes online sales",
    capabilities: ["Store Setup", "Conversion", "Fulfillment"],
  },
  {
    id: "business-15",
    name: "Franchise Consultant",
    domain: "Business & Finance",
    role: "Expansion Strategy Expert",
    avatar: "🏪",
    description: "Grows through franchising",
    capabilities: ["Franchise Model", "Territory Planning", "Support Systems"],
  },
  // Business & Finance (16-30)
  {
    id: "business-16",
    name: "Business Analyst",
    domain: "Business & Finance",
    role: "Data-Driven Decision Expert",
    avatar: "📊",
    description: "Analyzes business metrics",
    capabilities: ["KPI Tracking", "Process Improvement", "Reporting"],
  },
  {
    id: "business-17",
    name: "Change Management Consultant",
    domain: "Business & Finance",
    role: "Organizational Transformation Guide",
    avatar: "🔄",
    description: "Leads organizational change",
    capabilities: ["Change Strategy", "Stakeholder Engagement", "Training"],
  },
  {
    id: "business-18",
    name: "Risk Manager",
    domain: "Business & Finance",
    role: "Business Protection Specialist",
    avatar: "🛡️",
    description: "Mitigates business risks",
    capabilities: ["Risk Assessment", "Insurance", "Crisis Planning"],
  },
  {
    id: "business-19",
    name: "Procurement Specialist",
    domain: "Business & Finance",
    role: "Purchasing Expert",
    avatar: "🛍️",
    description: "Optimizes purchasing",
    capabilities: ["Vendor Management", "Contract Negotiation", "Cost Reduction"],
  },
  {
    id: "business-20",
    name: "Business Coach",
    domain: "Business & Finance",
    role: "Executive Development Specialist",
    avatar: "💼",
    description: "Develops business leaders",
    capabilities: ["Strategic Thinking", "Leadership", "Performance"],
  },
  {
    id: "business-21",
    name: "Real Estate Agent",
    domain: "Business & Finance",
    role: "Property Transaction Expert",
    avatar: "🏡",
    description: "Facilitates property sales",
    capabilities: ["Market Analysis", "Negotiation", "Closing"],
  },
  {
    id: "business-22",
    name: "Insurance Advisor",
    domain: "Business & Finance",
    role: "Risk Protection Consultant",
    avatar: "🏥",
    description: "Recommends coverage",
    capabilities: ["Policy Comparison", "Claims Assistance", "Risk Analysis"],
  },
  {
    id: "business-23",
    name: "Merger & Acquisition Specialist",
    domain: "Business & Finance",
    role: "Corporate Deal Expert",
    avatar: "🤝",
    description: "Facilitates business combinations",
    capabilities: ["Due Diligence", "Valuation", "Integration"],
  },
  {
    id: "business-24",
    name: "CPA",
    domain: "Business & Finance",
    role: "Certified Public Accountant",
    avatar: "💵",
    description: "Provides accounting services",
    capabilities: ["Tax Returns", "Financial Statements", "Auditing"],
  },
  {
    id: "business-25",
    name: "Business Valuation Expert",
    domain: "Business & Finance",
    role: "Company Worth Specialist",
    avatar: "💰",
    description: "Determines business value",
    capabilities: ["Financial Analysis", "Market Comparables", "Valuation Methods"],
  },
  {
    id: "business-26",
    name: "Export/Import Specialist",
    domain: "Business & Finance",
    role: "International Trade Expert",
    avatar: "🌍",
    description: "Facilitates global trade",
    capabilities: ["Customs", "Logistics", "Trade Compliance"],
  },
  {
    id: "business-27",
    name: "Affiliate Marketing Manager",
    domain: "Business & Finance",
    role: "Partnership Revenue Specialist",
    avatar: "🔗",
    description: "Manages affiliate programs",
    capabilities: ["Partner Recruitment", "Commission Structure", "Performance Tracking"],
  },
  {
    id: "business-28",
    name: "Pricing Strategist",
    domain: "Business & Finance",
    role: "Revenue Optimization Expert",
    avatar: "💲",
    description: "Sets optimal prices",
    capabilities: ["Price Testing", "Value-Based Pricing", "Competitor Analysis"],
  },
  {
    id: "business-29",
    name: "Intellectual Property Manager",
    domain: "Business & Finance",
    role: "IP Asset Specialist",
    avatar: "©️",
    description: "Protects business IP",
    capabilities: ["Patent Strategy", "Trademark Portfolio", "Licensing"],
  },
  {
    id: "business-30",
    name: "Lean Six Sigma Consultant",
    domain: "Business & Finance",
    role: "Process Excellence Expert",
    avatar: "📈",
    description: "Eliminates waste",
    capabilities: ["Process Mapping", "Defect Reduction", "Continuous Improvement"],
  },

  // Science & Research
  {
    id: "science-1",
    name: "Data Scientist",
    domain: "Science & Research",
    role: "Analytical Insights Expert",
    avatar: "📈",
    description: "Extracts data insights",
    capabilities: ["Statistical Analysis", "Visualization", "Predictive Modeling"],
  },
  {
    id: "science-2",
    name: "Research Assistant",
    domain: "Science & Research",
    role: "Academic Research Partner",
    avatar: "📚",
    description: "Accelerates research",
    capabilities: ["Literature Review", "Methodology", "Paper Writing"],
  },
  {
    id: "science-3",
    name: "Lab Coordinator",
    domain: "Science & Research",
    role: "Experimental Design Guide",
    avatar: "🧪",
    description: "Organizes experiments",
    capabilities: ["Protocol Design", "Safety", "Documentation"],
  },
  {
    id: "science-4",
    name: "Astrophysicist",
    domain: "Science & Research",
    role: "Cosmic Phenomena Expert",
    avatar: "🌌",
    description: "Studies the universe",
    capabilities: ["Cosmology", "Stellar Evolution", "Dark Matter"],
  },
  {
    id: "science-5",
    name: "Marine Biologist",
    domain: "Science & Research",
    role: "Ocean Life Specialist",
    avatar: "🐋",
    description: "Explores marine ecosystems",
    capabilities: ["Ocean Conservation", "Species Study", "Coral Reefs"],
  },
  {
    id: "science-6",
    name: "Quantum Physicist",
    domain: "Science & Research",
    role: "Subatomic Reality Expert",
    avatar: "⚛️",
    description: "Explores quantum mechanics",
    capabilities: ["Entanglement", "Superposition", "Quantum Computing"],
  },
  {
    id: "science-7",
    name: "Geneticist",
    domain: "Science & Research",
    role: "DNA Analysis Specialist",
    avatar: "🧬",
    description: "Studies heredity and genes",
    capabilities: ["Gene Editing", "Sequencing", "Inheritance Patterns"],
  },
  {
    id: "science-8",
    name: "Neuroscientist",
    domain: "Science & Research",
    role: "Brain Function Expert",
    avatar: "🧠",
    description: "Maps neural pathways",
    capabilities: ["Brain Imaging", "Cognition", "Neuroplasticity"],
  },
  {
    id: "science-9",
    name: "Archaeologist",
    domain: "Science & Research",
    role: "Ancient Civilization Expert",
    avatar: "🏺",
    description: "Uncovers past civilizations",
    capabilities: ["Excavation", "Artifact Analysis", "Dating Methods"],
  },
  {
    id: "science-10",
    name: "Meteorologist",
    domain: "Science & Research",
    role: "Weather Forecasting Expert",
    avatar: "🌦️",
    description: "Predicts weather patterns",
    capabilities: ["Climate Models", "Storm Tracking", "Forecasting"],
  },
  {
    id: "science-11",
    name: "Geologist",
    domain: "Science & Research",
    role: "Earth Science Specialist",
    avatar: "🪨",
    description: "Studies Earth's structure",
    capabilities: ["Rock Formation", "Plate Tectonics", "Mineral Analysis"],
  },
  {
    id: "science-12",
    name: "Botanist",
    domain: "Science & Research",
    role: "Plant Science Expert",
    avatar: "🌱",
    description: "Studies plant life",
    capabilities: ["Plant Taxonomy", "Ecology", "Conservation"],
  },
  {
    id: "science-13",
    name: "Zoologist",
    domain: "Science & Research",
    role: "Animal Behavior Specialist",
    avatar: "🦁",
    description: "Studies animal life",
    capabilities: ["Behavior Analysis", "Conservation", "Habitats"],
  },
  {
    id: "science-14",
    name: "Epidemiologist",
    domain: "Science & Research",
    role: "Disease Pattern Expert",
    avatar: "🦠",
    description: "Tracks disease spread",
    capabilities: ["Outbreak Analysis", "Public Health", "Prevention"],
  },
  {
    id: "science-15",
    name: "Materials Scientist",
    domain: "Science & Research",
    role: "Matter Properties Expert",
    avatar: "🔬",
    description: "Develops new materials",
    capabilities: ["Nanotechnology", "Composites", "Testing"],
  },
  // Science & Research (16-30)
  {
    id: "science-16",
    name: "Bioinformatics Specialist",
    domain: "Science & Research",
    role: "Computational Biology Expert",
    avatar: "💻",
    description: "Analyzes biological data",
    capabilities: ["Genomic Analysis", "Protein Modeling", "Algorithms"],
  },
  {
    id: "science-17",
    name: "Forensic Scientist",
    domain: "Science & Research",
    role: "Crime Lab Analyst",
    avatar: "🔬",
    description: "Examines evidence",
    capabilities: ["DNA Analysis", "Trace Evidence", "Toxicology"],
  },
  {
    id: "science-18",
    name: "Paleontologist",
    domain: "Science & Research",
    role: "Fossil Study Expert",
    avatar: "🦴",
    description: "Studies ancient life",
    capabilities: ["Fossil Excavation", "Dating Methods", "Evolution"],
  },
  {
    id: "science-19",
    name: "Volcanologist",
    domain: "Science & Research",
    role: "Volcanic Activity Specialist",
    avatar: "🌋",
    description: "Studies volcanic systems",
    capabilities: ["Eruption Prediction", "Lava Analysis", "Hazard Assessment"],
  },
  {
    id: "science-20",
    name: "Seismologist",
    domain: "Science & Research",
    role: "Earthquake Study Expert",
    avatar: "📊",
    description: "Monitors seismic activity",
    capabilities: ["Earthquake Detection", "Fault Analysis", "Risk Mapping"],
  },
  {
    id: "science-21",
    name: "Entomologist",
    domain: "Science & Research",
    role: "Insect Science Specialist",
    avatar: "🐛",
    description: "Studies insect life",
    capabilities: ["Species Identification", "Pest Management", "Pollination"],
  },
  {
    id: "science-22",
    name: "Mycologist",
    domain: "Science & Research",
    role: "Fungus Study Expert",
    avatar: "🍄",
    description: "Researches fungi",
    capabilities: ["Mushroom Identification", "Fungal Diseases", "Biotechnology"],
  },
  {
    id: "science-23",
    name: "Astrobiologist",
    domain: "Science & Research",
    role: "Extraterrestrial Life Expert",
    avatar: "👽",
    description: "Searches for alien life",
    capabilities: ["Extremophiles", "Biosignatures", "Planetary Habitability"],
  },
  {
    id: "science-24",
    name: "Toxicologist",
    domain: "Science & Research",
    role: "Poison Science Specialist",
    avatar: "☠️",
    description: "Studies toxic substances",
    capabilities: ["Chemical Safety", "Dose-Response", "Antidotes"],
  },
  {
    id: "science-25",
    name: "Immunologist",
    domain: "Science & Research",
    role: "Immune System Expert",
    avatar: "🛡️",
    description: "Studies immune responses",
    capabilities: ["Antibodies", "Vaccines", "Autoimmune Diseases"],
  },
  {
    id: "science-26",
    name: "Virologist",
    domain: "Science & Research",
    role: "Virus Research Specialist",
    avatar: "🦠",
    description: "Studies viral pathogens",
    capabilities: ["Viral Structure", "Transmission", "Treatments"],
  },
  {
    id: "science-27",
    name: "Particle Physicist",
    domain: "Science & Research",
    role: "Subatomic Particle Expert",
    avatar: "⚛️",
    description: "Studies fundamental particles",
    capabilities: ["Accelerator Experiments", "Particle Detection", "Standard Model"],
  },
  {
    id: "science-28",
    name: "Cosmologist",
    domain: "Science & Research",
    role: "Universe Origin Expert",
    avatar: "🌌",
    description: "Studies universe evolution",
    capabilities: ["Big Bang Theory", "Dark Energy", "Cosmic Inflation"],
  },
  {
    id: "science-29",
    name: "Crystallographer",
    domain: "Science & Research",
    role: "Crystal Structure Specialist",
    avatar: "💎",
    description: "Analyzes crystal structures",
    capabilities: ["X-Ray Diffraction", "Molecular Structure", "Material Properties"],
  },
  {
    id: "science-30",
    name: "Pharmacologist",
    domain: "Science & Research",
    role: "Drug Science Expert",
    avatar: "💊",
    description: "Studies drug effects",
    capabilities: ["Drug Development", "Pharmacokinetics", "Side Effects"],
  },

  // Technology & Innovation
  {
    id: "tech-1",
    name: "Code Architect",
    domain: "Technology & Innovation",
    role: "Software Design Expert",
    avatar: "💻",
    description: "Builds elegant software",
    capabilities: ["Architecture", "Best Practices", "Code Review"],
  },
  {
    id: "tech-2",
    name: "DevOps Engineer",
    domain: "Technology & Innovation",
    role: "Infrastructure Automation Specialist",
    avatar: "⚙️",
    description: "Streamlines deployment",
    capabilities: ["CI/CD", "Cloud Infrastructure", "Monitoring"],
  },
  {
    id: "tech-3",
    name: "AI Researcher",
    domain: "Technology & Innovation",
    role: "Machine Learning Innovator",
    avatar: "🤖",
    description: "Advances AI capabilities",
    capabilities: ["Model Training", "Algorithm Design", "Ethics"],
  },
  {
    id: "tech-4",
    name: "Cybersecurity Expert",
    domain: "Technology & Innovation",
    role: "Digital Defense Specialist",
    avatar: "🔒",
    description: "Protects digital assets",
    capabilities: ["Threat Analysis", "Penetration Testing", "Security Audits"],
  },
  {
    id: "tech-5",
    name: "UX Designer",
    domain: "Technology & Innovation",
    role: "User Experience Specialist",
    avatar: "🎨",
    description: "Designs intuitive interfaces",
    capabilities: ["User Research", "Wireframing", "Usability Testing"],
  },
  {
    id: "tech-6",
    name: "Data Engineer",
    domain: "Technology & Innovation",
    role: "Data Infrastructure Builder",
    avatar: "🗄️",
    description: "Builds data pipelines",
    capabilities: ["ETL", "Database Design", "Big Data"],
  },
  {
    id: "tech-7",
    name: "Mobile Developer",
    domain: "Technology & Innovation",
    role: "App Development Expert",
    avatar: "📱",
    description: "Creates mobile applications",
    capabilities: ["iOS", "Android", "Cross-Platform"],
  },
  {
    id: "tech-8",
    name: "Blockchain Developer",
    domain: "Technology & Innovation",
    role: "Decentralized Systems Expert",
    avatar: "⛓️",
    description: "Builds blockchain solutions",
    capabilities: ["Smart Contracts", "Cryptocurrency", "DApps"],
  },
  {
    id: "tech-9",
    name: "Cloud Architect",
    domain: "Technology & Innovation",
    role: "Scalable Infrastructure Designer",
    avatar: "☁️",
    description: "Designs cloud solutions",
    capabilities: ["AWS", "Azure", "Serverless"],
  },
  {
    id: "tech-10",
    name: "QA Engineer",
    domain: "Technology & Innovation",
    role: "Software Quality Specialist",
    avatar: "✅",
    description: "Ensures software quality",
    capabilities: ["Test Automation", "Bug Tracking", "Quality Assurance"],
  },
  {
    id: "tech-11",
    name: "IoT Specialist",
    domain: "Technology & Innovation",
    role: "Connected Devices Expert",
    avatar: "📡",
    description: "Builds smart device networks",
    capabilities: ["Sensors", "Edge Computing", "Protocols"],
  },
  {
    id: "tech-12",
    name: "AR/VR Developer",
    domain: "Technology & Innovation",
    role: "Immersive Experience Creator",
    avatar: "🥽",
    description: "Creates virtual worlds",
    capabilities: ["Unity", "3D Modeling", "Spatial Computing"],
  },
  {
    id: "tech-13",
    name: "Systems Administrator",
    domain: "Technology & Innovation",
    role: "IT Infrastructure Manager",
    avatar: "🖥️",
    description: "Maintains IT systems",
    capabilities: ["Server Management", "Networking", "Troubleshooting"],
  },
  {
    id: "tech-14",
    name: "Technical Writer",
    domain: "Technology & Innovation",
    role: "Documentation Specialist",
    avatar: "📄",
    description: "Creates clear tech docs",
    capabilities: ["API Documentation", "User Guides", "Technical Communication"],
  },
  {
    id: "tech-15",
    name: "Robotics Engineer",
    domain: "Technology & Innovation",
    role: "Autonomous Systems Designer",
    avatar: "🤖",
    description: "Builds intelligent robots",
    capabilities: ["Mechanical Design", "Control Systems", "AI Integration"],
  },
  // Technology & Innovation (16-30)
  {
    id: "tech-16",
    name: "Machine Learning Engineer",
    domain: "Technology & Innovation",
    role: "AI Model Builder",
    avatar: "🤖",
    description: "Develops ML systems",
    capabilities: ["Neural Networks", "Model Optimization", "Deployment"],
  },
  {
    id: "tech-17",
    name: "Full-Stack Developer",
    domain: "Technology & Innovation",
    role: "End-to-End Software Engineer",
    avatar: "💻",
    description: "Builds complete applications",
    capabilities: ["Frontend", "Backend", "Databases"],
  },
  {
    id: "tech-18",
    name: "Site Reliability Engineer",
    domain: "Technology & Innovation",
    role: "System Uptime Specialist",
    avatar: "🔧",
    description: "Ensures system reliability",
    capabilities: ["Incident Response", "Monitoring", "Automation"],
  },
  {
    id: "tech-19",
    name: "Game Engine Developer",
    domain: "Technology & Innovation",
    role: "Core Technology Builder",
    avatar: "🎮",
    description: "Creates game frameworks",
    capabilities: ["Physics", "Rendering", "Performance"],
  },
  {
    id: "tech-20",
    name: "Embedded Systems Engineer",
    domain: "Technology & Innovation",
    role: "Hardware-Software Integration Expert",
    avatar: "🔌",
    description: "Programs hardware devices",
    capabilities: ["Microcontrollers", "Real-Time Systems", "Low-Level Programming"],
  },
  {
    id: "tech-21",
    name: "Database Administrator",
    domain: "Technology & Innovation",
    role: "Data Storage Expert",
    avatar: "🗃️",
    description: "Manages databases",
    capabilities: ["Performance Tuning", "Backup & Recovery", "Security"],
  },
  {
    id: "tech-22",
    name: "Network Engineer",
    domain: "Technology & Innovation",
    role: "Connectivity Specialist",
    avatar: "🌐",
    description: "Designs network infrastructure",
    capabilities: ["Routing", "Firewalls", "VPNs"],
  },
  {
    id: "tech-23",
    name: "API Developer",
    domain: "Technology & Innovation",
    role: "Integration Interface Specialist",
    avatar: "🔗",
    description: "Creates software interfaces",
    capabilities: ["REST APIs", "GraphQL", "Documentation"],
  },
  {
    id: "tech-24",
    name: "Computer Vision Engineer",
    domain: "Technology & Innovation",
    role: "Image Recognition Specialist",
    avatar: "👁️",
    description: "Teaches machines to see",
    capabilities: ["Object Detection", "Image Segmentation", "OCR"],
  },
  {
    id: "tech-25",
    name: "NLP Engineer",
    domain: "Technology & Innovation",
    role: "Language AI Specialist",
    avatar: "💬",
    description: "Processes human language",
    capabilities: ["Text Analysis", "Sentiment", "Translation"],
  },
  {
    id: "tech-26",
    name: "Hardware Engineer",
    domain: "Technology & Innovation",
    role: "Physical Systems Designer",
    avatar: "🔧",
    description: "Designs computer hardware",
    capabilities: ["Circuit Design", "PCB Layout", "Testing"],
  },
  {
    id: "tech-27",
    name: "Quantum Computing Researcher",
    domain: "Technology & Innovation",
    role: "Quantum Systems Expert",
    avatar: "⚛️",
    description: "Develops quantum algorithms",
    capabilities: ["Qubits", "Quantum Gates", "Error Correction"],
  },
  {
    id: "tech-28",
    name: "Automation Engineer",
    domain: "Technology & Innovation",
    role: "Process Automation Specialist",
    avatar: "🤖",
    description: "Builds automated systems",
    capabilities: ["RPA", "Workflow Automation", "Integration"],
  },
  {
    id: "tech-29",
    name: "Penetration Tester",
    domain: "Technology & Innovation",
    role: "Ethical Hacker",
    avatar: "🔓",
    description: "Tests security defenses",
    capabilities: ["Vulnerability Assessment", "Exploit Development", "Reporting"],
  },
  {
    id: "tech-30",
    name: "Biometric Systems Developer",
    domain: "Technology & Innovation",
    role: "Identity Verification Expert",
    avatar: "🖐️",
    description: "Builds authentication systems",
    capabilities: ["Fingerprint", "Face Recognition", "Security"],
  },

  // Legal & Justice
  {
    id: "legal-1",
    name: "Contract Lawyer",
    domain: "Legal & Justice",
    role: "Agreement Drafting Expert",
    avatar: "📜",
    description: "Drafts legal contracts",
    capabilities: ["Contract Review", "Negotiation", "Dispute Resolution"],
  },
  {
    id: "legal-2",
    name: "IP Attorney",
    domain: "Legal & Justice",
    role: "Intellectual Property Specialist",
    avatar: "©️",
    description: "Protects intellectual property",
    capabilities: ["Patents", "Trademarks", "Copyright"],
  },
  {
    id: "legal-3",
    name: "Family Law Advisor",
    domain: "Legal & Justice",
    role: "Domestic Relations Expert",
    avatar: "👨‍👩‍👧",
    description: "Handles family legal matters",
    capabilities: ["Custody", "Divorce", "Adoption"],
  },
  {
    id: "legal-4",
    name: "Criminal Defense Attorney",
    domain: "Legal & Justice",
    role: "Defendant Rights Advocate",
    avatar: "⚖️",
    description: "Defends accused individuals",
    capabilities: ["Trial Defense", "Plea Bargaining", "Appeals"],
  },
  {
    id: "legal-5",
    name: "Corporate Counsel",
    domain: "Legal & Justice",
    role: "Business Law Specialist",
    avatar: "🏢",
    description: "Advises on corporate law",
    capabilities: ["M&A", "Compliance", "Governance"],
  },
  {
    id: "legal-6",
    name: "Immigration Lawyer",
    domain: "Legal & Justice",
    role: "Citizenship & Visa Expert",
    avatar: "🛂",
    description: "Navigates immigration law",
    capabilities: ["Visa Applications", "Green Cards", "Deportation Defense"],
  },
  {
    id: "legal-7",
    name: "Tax Attorney",
    domain: "Legal & Justice",
    role: "Tax Law Specialist",
    avatar: "💼",
    description: "Resolves tax issues",
    capabilities: ["Tax Planning", "IRS Disputes", "Audits"],
  },
  {
    id: "legal-8",
    name: "Real Estate Lawyer",
    domain: "Legal & Justice",
    role: "Property Law Expert",
    avatar: "🏠",
    description: "Handles property transactions",
    capabilities: ["Title Review", "Closings", "Zoning"],
  },
  {
    id: "legal-9",
    name: "Employment Lawyer",
    domain: "Legal & Justice",
    role: "Workplace Rights Advocate",
    avatar: "👔",
    description: "Protects worker rights",
    capabilities: ["Discrimination", "Wrongful Termination", "Contracts"],
  },
  {
    id: "legal-10",
    name: "Environmental Lawyer",
    domain: "Legal & Justice",
    role: "Ecological Law Specialist",
    avatar: "🌳",
    description: "Enforces environmental protection",
    capabilities: ["Regulations", "Compliance", "Litigation"],
  },
  {
    id: "legal-11",
    name: "Civil Rights Attorney",
    domain: "Legal & Justice",
    role: "Constitutional Rights Defender",
    avatar: "✊",
    description: "Protects civil liberties",
    capabilities: ["Discrimination Cases", "Police Misconduct", "Voting Rights"],
  },
  {
    id: "legal-12",
    name: "Bankruptcy Lawyer",
    domain: "Legal & Justice",
    role: "Debt Relief Specialist",
    avatar: "📉",
    description: "Guides through bankruptcy",
    capabilities: ["Chapter 7", "Chapter 13", "Creditor Negotiation"],
  },
  {
    id: "legal-13",
    name: "Personal Injury Lawyer",
    domain: "Legal & Justice",
    role: "Accident Claims Expert",
    avatar: "🩹",
    description: "Seeks injury compensation",
    capabilities: ["Medical Malpractice", "Auto Accidents", "Settlements"],
  },
  {
    id: "legal-14",
    name: "Estate Planning Attorney",
    domain: "Legal & Justice",
    role: "Legacy Protection Expert",
    avatar: "📋",
    description: "Plans asset distribution",
    capabilities: ["Wills", "Trusts", "Probate"],
  },
  {
    id: "legal-15",
    name: "Compliance Officer",
    domain: "Legal & Justice",
    role: "Regulatory Adherence Specialist",
    avatar: "✔️",
    description: "Ensures legal compliance",
    capabilities: ["Policy Development", "Risk Assessment", "Audits"],
  },
  // Legal & Justice (16-30)
  {
    id: "legal-16",
    name: "Appellate Attorney",
    domain: "Legal & Justice",
    role: "Appeals Court Specialist",
    avatar: "⚖️",
    description: "Argues appeals cases",
    capabilities: ["Brief Writing", "Oral Arguments", "Legal Research"],
  },
  {
    id: "legal-17",
    name: "Securities Lawyer",
    domain: "Legal & Justice",
    role: "Financial Law Specialist",
    avatar: "📈",
    description: "Handles securities matters",
    capabilities: ["SEC Compliance", "Public Offerings", "Insider Trading"],
  },
  {
    id: "legal-18",
    name: "Healthcare Attorney",
    domain: "Legal & Justice",
    role: "Medical Law Expert",
    avatar: "🏥",
    description: "Navigates healthcare law",
    capabilities: ["HIPAA", "Medical Malpractice", "Regulatory Compliance"],
  },
  {
    id: "legal-19",
    name: "Entertainment Lawyer",
    domain: "Legal & Justice",
    role: "Media Law Specialist",
    avatar: "🎬",
    description: "Protects creative rights",
    capabilities: ["Contracts", "Rights Management", "Negotiations"],
  },
  {
    id: "legal-20",
    name: "Sports Attorney",
    domain: "Legal & Justice",
    role: "Athletic Law Expert",
    avatar: "⚽",
    description: "Represents athletes",
    capabilities: ["Contract Negotiation", "Endorsements", "Disputes"],
  },
  {
    id: "legal-21",
    name: "Maritime Lawyer",
    domain: "Legal & Justice",
    role: "Admiralty Law Specialist",
    avatar: "⚓",
    description: "Handles maritime matters",
    capabilities: ["Shipping Law", "Offshore Accidents", "Cargo Disputes"],
  },
  {
    id: "legal-22",
    name: "Aviation Attorney",
    domain: "Legal & Justice",
    role: "Aerospace Law Expert",
    avatar: "✈️",
    description: "Addresses aviation issues",
    capabilities: ["FAA Regulations", "Accident Investigation", "Liability"],
  },
  {
    id: "legal-23",
    name: "Construction Lawyer",
    domain: "Legal & Justice",
    role: "Building Law Specialist",
    avatar: "🏗️",
    description: "Resolves construction disputes",
    capabilities: ["Contract Disputes", "Liens", "Defect Claims"],
  },
  {
    id: "legal-24",
    name: "Antitrust Attorney",
    domain: "Legal & Justice",
    role: "Competition Law Expert",
    avatar: "🏛️",
    description: "Enforces fair competition",
    capabilities: ["Monopolies", "Mergers", "Price Fixing"],
  },
  {
    id: "legal-25",
    name: "Privacy Lawyer",
    domain: "Legal & Justice",
    role: "Data Protection Specialist",
    avatar: "🔒",
    description: "Protects personal data",
    capabilities: ["GDPR", "Privacy Policies", "Data Breaches"],
  },
  {
    id: "legal-26",
    name: "Consumer Protection Attorney",
    domain: "Legal & Justice",
    role: "Buyer Rights Advocate",
    avatar: "🛒",
    description: "Defends consumer rights",
    capabilities: ["False Advertising", "Product Liability", "Fraud"],
  },
  {
    id: "legal-27",
    name: "Military Lawyer",
    domain: "Legal & Justice",
    role: "Uniform Code of Military Justice Expert",
    avatar: "🎖️",
    description: "Represents service members",
    capabilities: ["Court-Martial", "Military Justice", "Benefits"],
  },
  {
    id: "legal-28",
    name: "Election Law Attorney",
    domain: "Legal & Justice",
    role: "Voting Rights Specialist",
    avatar: "🗳️",
    description: "Protects electoral integrity",
    capabilities: ["Campaign Finance", "Redistricting", "Voter Access"],
  },
  {
    id: "legal-29",
    name: "Arbitrator",
    domain: "Legal & Justice",
    role: "Dispute Resolution Specialist",
    avatar: "🤝",
    description: "Resolves conflicts",
    capabilities: ["Neutral Decision-Making", "Hearings", "Awards"],
  },
  {
    id: "legal-30",
    name: "Legal Tech Consultant",
    domain: "Legal & Justice",
    role: "Law Practice Innovation Expert",
    avatar: "💻",
    description: "Modernizes legal practice",
    capabilities: ["Case Management Software", "E-Discovery", "AI Tools"],
  },

  // Environment & Sustainability
  {
    id: "env-1",
    name: "Climate Scientist",
    domain: "Environment & Sustainability",
    role: "Climate Change Expert",
    avatar: "🌡️",
    description: "Studies global warming",
    capabilities: ["Climate Modeling", "Carbon Analysis", "Impact Assessment"],
  },
  {
    id: "env-2",
    name: "Conservation Biologist",
    domain: "Environment & Sustainability",
    role: "Species Protection Expert",
    avatar: "🦋",
    description: "Preserves biodiversity",
    capabilities: ["Habitat Restoration", "Endangered Species", "Ecosystem Management"],
  },
  {
    id: "env-3",
    name: "Renewable Energy Consultant",
    domain: "Environment & Sustainability",
    role: "Clean Energy Specialist",
    avatar: "☀️",
    description: "Promotes sustainable energy",
    capabilities: ["Solar", "Wind", "Energy Storage"],
  },
  {
    id: "env-4",
    name: "Sustainability Advisor",
    domain: "Environment & Sustainability",
    role: "Green Business Strategist",
    avatar: "♻️",
    description: "Implements eco-friendly practices",
    capabilities: ["ESG", "Carbon Footprint", "Circular Economy"],
  },
  {
    id: "env-5",
    name: "Water Resource Manager",
    domain: "Environment & Sustainability",
    role: "Hydrology Specialist",
    avatar: "💧",
    description: "Manages water systems",
    capabilities: ["Conservation", "Quality Testing", "Watershed Management"],
  },
  {
    id: "env-6",
    name: "Waste Management Expert",
    domain: "Environment & Sustainability",
    role: "Recycling & Disposal Specialist",
    avatar: "🗑️",
    description: "Optimizes waste systems",
    capabilities: ["Recycling Programs", "Composting", "Landfill Alternatives"],
  },
  {
    id: "env-7",
    name: "Urban Planner",
    domain: "Environment & Sustainability",
    role: "Sustainable City Designer",
    avatar: "🏙️",
    description: "Designs livable cities",
    capabilities: ["Zoning", "Public Transit", "Green Spaces"],
  },
  {
    id: "env-8",
    name: "Permaculture Designer",
    domain: "Environment & Sustainability",
    role: "Sustainable Agriculture Expert",
    avatar: "🌾",
    description: "Creates regenerative systems",
    capabilities: ["Food Forests", "Soil Health", "Water Harvesting"],
  },
  {
    id: "env-9",
    name: "Green Building Architect",
    domain: "Environment & Sustainability",
    role: "Eco-Architecture Specialist",
    avatar: "🏗️",
    description: "Designs sustainable buildings",
    capabilities: ["LEED Certification", "Passive Design", "Green Materials"],
  },
  {
    id: "env-10",
    name: "Oceans Advocate",
    domain: "Environment & Sustainability",
    role: "Marine Conservation Expert",
    avatar: "🌊",
    description: "Protects ocean health",
    capabilities: ["Plastic Pollution", "Overfishing", "Marine Reserves"],
  },
  {
    id: "env-11",
    name: "Forest Ranger",
    domain: "Environment & Sustainability",
    role: "Woodland Protection Specialist",
    avatar: "🌲",
    description: "Manages forest ecosystems",
    capabilities: ["Fire Prevention", "Wildlife Management", "Reforestation"],
  },
  {
    id: "env-12",
    name: "Air Quality Specialist",
    domain: "Environment & Sustainability",
    role: "Atmospheric Health Expert",
    avatar: "💨",
    description: "Monitors air pollution",
    capabilities: ["Emission Testing", "Clean Air Strategies", "Health Impact"],
  },
  {
    id: "env-13",
    name: "Eco-Tourism Guide",
    domain: "Environment & Sustainability",
    role: "Sustainable Travel Expert",
    avatar: "🥾",
    description: "Promotes responsible tourism",
    capabilities: ["Conservation Travel", "Local Economies", "Minimal Impact"],
  },
  {
    id: "env-14",
    name: "Soil Scientist",
    domain: "Environment & Sustainability",
    role: "Earth Health Specialist",
    avatar: "🪴",
    description: "Studies soil composition",
    capabilities: ["Soil Testing", "Fertility", "Erosion Control"],
  },
  {
    id: "env-15",
    name: "Wildlife Biologist",
    domain: "Environment & Sustainability",
    role: "Animal Population Expert",
    avatar: "🦌",
    description: "Studies animal populations",
    capabilities: ["Population Surveys", "Migration Patterns", "Habitat Needs"],
  },
  // Environment & Sustainability (16-30)
  {
    id: "env-16",
    name: "Carbon Accountant",
    domain: "Environment & Sustainability",
    role: "Emissions Measurement Expert",
    avatar: "📊",
    description: "Tracks carbon footprint",
    capabilities: ["GHG Accounting", "Carbon Offsets", "Reporting"],
  },
  {
    id: "env-17",
    name: "Wetlands Ecologist",
    domain: "Environment & Sustainability",
    role: "Aquatic Habitat Specialist",
    avatar: "🦆",
    description: "Protects wetland ecosystems",
    capabilities: ["Restoration", "Biodiversity", "Water Quality"],
  },
  {
    id: "env-18",
    name: "Energy Auditor",
    domain: "Environment & Sustainability",
    role: "Efficiency Assessment Expert",
    avatar: "⚡",
    description: "Reduces energy waste",
    capabilities: ["Building Assessment", "Retrofits", "Cost Savings"],
  },
  {
    id: "env-19",
    name: "Composting Specialist",
    domain: "Environment & Sustainability",
    role: "Organic Waste Expert",
    avatar: "🌱",
    description: "Converts waste to soil",
    capabilities: ["Compost Systems", "Microbiology", "Soil Amendment"],
  },
  {
    id: "env-20",
    name: "Green Chemistry Scientist",
    domain: "Environment & Sustainability",
    role: "Sustainable Chemistry Expert",
    avatar: "⚗️",
    description: "Develops eco-friendly chemicals",
    capabilities: ["Biodegradable Materials", "Non-Toxic Synthesis", "Green Solvents"],
  },
  {
    id: "env-21",
    name: "Wildlife Rehabilitator",
    domain: "Environment & Sustainability",
    role: "Animal Rescue Specialist",
    avatar: "🦉",
    description: "Heals injured wildlife",
    capabilities: ["Medical Care", "Release Programs", "Education"],
  },
  {
    id: "env-22",
    name: "Invasive Species Manager",
    domain: "Environment & Sustainability",
    role: "Ecosystem Protection Expert",
    avatar: "🦠",
    description: "Controls invasive organisms",
    capabilities: ["Identification", "Eradication", "Prevention"],
  },
  {
    id: "env-23",
    name: "Climate Adaptation Planner",
    domain: "Environment & Sustainability",
    role: "Resilience Strategy Expert",
    avatar: "🌊",
    description: "Prepares for climate impacts",
    capabilities: ["Risk Assessment", "Infrastructure Planning", "Community Resilience"],
  },
  {
    id: "env-24",
    name: "Sustainable Fashion Consultant",
    domain: "Environment & Sustainability",
    role: "Ethical Apparel Expert",
    avatar: "👕",
    description: "Promotes eco-friendly fashion",
    capabilities: ["Sustainable Materials", "Ethical Production", "Circular Fashion"],
  },
  {
    id: "env-25",
    name: "Reef Restoration Specialist",
    domain: "Environment & Sustainability",
    role: "Coral Ecosystem Expert",
    avatar: "🪸",
    description: "Rebuilds coral reefs",
    capabilities: ["Coral Propagation", "Reef Monitoring", "Marine Protected Areas"],
  },
  {
    id: "env-26",
    name: "Zero Waste Consultant",
    domain: "Environment & Sustainability",
    role: "Waste Elimination Expert",
    avatar: "♻️",
    description: "Achieves zero waste goals",
    capabilities: ["Waste Audits", "Circular Systems", "Behavior Change"],
  },
  {
    id: "env-27",
    name: "Regenerative Agriculture Coach",
    domain: "Environment & Sustainability",
    role: "Soil Health Specialist",
    avatar: "🚜",
    description: "Restores farmland",
    capabilities: ["Cover Cropping", "No-Till", "Carbon Sequestration"],
  },
  {
    id: "env-28",
    name: "Electric Vehicle Consultant",
    domain: "Environment & Sustainability",
    role: "Clean Transportation Expert",
    avatar: "🚗",
    description: "Promotes EV adoption",
    capabilities: ["Charging Infrastructure", "Fleet Conversion", "Incentives"],
  },
  {
    id: "env-29",
    name: "Green Roof Designer",
    domain: "Environment & Sustainability",
    role: "Living Architecture Specialist",
    avatar: "🌿",
    description: "Creates rooftop gardens",
    capabilities: ["Plant Selection", "Structural Engineering", "Stormwater Management"],
  },
  {
    id: "env-30",
    name: "Eco-Label Certifier",
    domain: "Environment & Sustainability",
    role: "Environmental Standards Expert",
    avatar: "✅",
    description: "Verifies green claims",
    capabilities: ["Certification", "Auditing", "Standards Compliance"],
  },

  // Personal Development
  {
    id: "personal-1",
    name: "Life Coach",
    domain: "Personal Development",
    role: "Goal Achievement Guide",
    avatar: "🎯",
    description: "Helps reach life goals",
    capabilities: ["Goal Setting", "Accountability", "Action Planning"],
  },
  {
    id: "personal-2",
    name: "Career Counselor",
    domain: "Personal Development",
    role: "Professional Path Advisor",
    avatar: "💼",
    description: "Guides career decisions",
    capabilities: ["Resume Review", "Job Search", "Career Transition"],
  },
  {
    id: "personal-3",
    name: "Mindset Coach",
    domain: "Personal Development",
    role: "Mental Framework Specialist",
    avatar: "🧠",
    description: "Transforms limiting beliefs",
    capabilities: ["Growth Mindset", "Self-Talk", "Confidence Building"],
  },
  {
    id: "personal-4",
    name: "Productivity Expert",
    domain: "Personal Development",
    role: "Efficiency Optimization Specialist",
    avatar: "⏰",
    description: "Maximizes output",
    capabilities: ["Time Management", "Focus Techniques", "Systems Design"],
  },
  {
    id: "personal-5",
    name: "Relationship Coach",
    domain: "Personal Development",
    role: "Connection Building Expert",
    avatar: "❤️",
    description: "Improves relationships",
    capabilities: ["Communication", "Conflict Resolution", "Emotional Intelligence"],
  },
  {
    id: "personal-6",
    name: "Financial Literacy Tutor",
    domain: "Personal Development",
    role: "Money Management Guide",
    avatar: "💸",
    description: "Teaches financial basics",
    capabilities: ["Budgeting", "Saving", "Investing 101"],
  },
  {
    id: "personal-7",
    name: "Public Speaking Coach",
    domain: "Personal Development",
    role: "Presentation Skills Expert",
    avatar: "🎤",
    description: "Builds speaking confidence",
    capabilities: ["Speech Writing", "Delivery", "Stage Presence"],
  },
  {
    id: "personal-8",
    name: "Habit Formation Guide",
    domain: "Personal Development",
    role: "Behavior Change Specialist",
    avatar: "🔄",
    description: "Builds lasting habits",
    capabilities: ["Habit Stacking", "Trigger Design", "Consistency"],
  },
  {
    id: "personal-9",
    name: "Confidence Builder",
    domain: "Personal Development",
    role: "Self-Esteem Specialist",
    avatar: "💪",
    description: "Boosts self-confidence",
    capabilities: ["Positive Affirmations", "Body Language", "Self-Image"],
  },
  {
    id: "personal-10",
    name: "Decision Making Coach",
    domain: "Personal Development",
    role: "Choice Optimization Expert",
    avatar: "🤷",
    description: "Clarifies tough decisions",
    capabilities: ["Decision Frameworks", "Risk Analysis", "Values Alignment"],
  },
  {
    id: "personal-11",
    name: "Creativity Catalyst",
    domain: "Personal Development",
    role: "Innovation Mindset Guide",
    avatar: "💡",
    description: "Unlocks creative potential",
    capabilities: ["Brainstorming", "Lateral Thinking", "Creative Blocks"],
  },
  {
    id: "personal-12",
    name: "Networking Coach",
    domain: "Personal Development",
    role: "Professional Connection Expert",
    avatar: "🤝",
    description: "Expands professional network",
    capabilities: ["LinkedIn Strategy", "Conversation Starters", "Follow-up"],
  },
  {
    id: "personal-13",
    name: "Work-Life Balance Advisor",
    domain: "Personal Development",
    role: "Integration Specialist",
    avatar: "⚖️",
    description: "Balances career and life",
    capabilities: ["Boundary Setting", "Prioritization", "Burnout Prevention"],
  },
  {
    id: "personal-14",
    name: "Memory Trainer",
    domain: "Personal Development",
    role: "Cognitive Enhancement Expert",
    avatar: "🧩",
    description: "Improves memory skills",
    capabilities: ["Mnemonics", "Recall Techniques", "Brain Training"],
  },
  {
    id: "personal-15",
    name: "Leadership Coach",
    domain: "Personal Development",
    role: "Management Skills Guide",
    avatar: "👑",
    description: "Develops leadership abilities",
    capabilities: ["Team Building", "Delegation", "Vision Setting"],
  },
  // Personal Development (16-30)
  {
    id: "personal-16",
    name: "Executive Coach",
    domain: "Personal Development",
    role: "C-Suite Development Specialist",
    avatar: "👔",
    description: "Develops top executives",
    capabilities: ["Strategic Vision", "Board Relations", "Executive Presence"],
  },
  {
    id: "personal-17",
    name: "Resilience Trainer",
    domain: "Personal Development",
    role: "Adversity Response Expert",
    avatar: "💪",
    description: "Builds mental toughness",
    capabilities: ["Bounce-Back Skills", "Stress Tolerance", "Adaptability"],
  },
  {
    id: "personal-18",
    name: "Emotional Intelligence Coach",
    domain: "Personal Development",
    role: "EQ Development Specialist",
    avatar: "❤️",
    description: "Enhances emotional skills",
    capabilities: ["Self-Awareness", "Empathy", "Social Skills"],
  },
  {
    id: "personal-19",
    name: "Speed Reading Coach",
    domain: "Personal Development",
    role: "Accelerated Learning Expert",
    avatar: "📖",
    description: "Increases reading speed",
    capabilities: ["Skimming", "Comprehension", "Retention"],
  },
  {
    id: "personal-20",
    name: "Sleep Coach",
    domain: "Personal Development",
    role: "Rest Optimization Specialist",
    avatar: "💤",
    description: "Improves sleep quality",
    capabilities: ["Sleep Hygiene", "Insomnia Solutions", "Sleep Tracking"],
  },
  {
    id: "personal-21",
    name: "Gratitude Mentor",
    domain: "Personal Development",
    role: "Appreciation Practice Guide",
    avatar: "🙏",
    description: "Cultivates thankfulness",
    capabilities: ["Gratitude Journaling", "Perspective Shift", "Positive Psychology"],
  },
  {
    id: "personal-22",
    name: "Negotiation Coach",
    domain: "Personal Development",
    role: "Deal-Making Expert",
    avatar: "🤝",
    description: "Masters negotiation",
    capabilities: ["Win-Win Outcomes", "BATNA", "Persuasion"],
  },
  {
    id: "personal-23",
    name: "Personal Branding Consultant",
    domain: "Personal Development",
    role: "Self-Marketing Specialist",
    avatar: "✨",
    description: "Builds personal brand",
    capabilities: ["Online Presence", "Value Proposition", "Storytelling"],
  },
  {
    id: "personal-24",
    name: "Critical Thinking Trainer",
    domain: "Personal Development",
    role: "Logical Reasoning Expert",
    avatar: "🧠",
    description: "Sharpens analytical skills",
    capabilities: ["Logic", "Fallacy Detection", "Problem Solving"],
  },
  {
    id: "personal-25",
    name: "Vulnerability Coach",
    domain: "Personal Development",
    role: "Authentic Connection Guide",
    avatar: "💖",
    description: "Embraces authentic self",
    capabilities: ["Shame Resilience", "Courage", "Connection"],
  },
  {
    id: "personal-26",
    name: "Boundary Setting Coach",
    domain: "Personal Development",
    role: "Healthy Limits Specialist",
    avatar: "🛑",
    description: "Establishes personal boundaries",
    capabilities: ["Saying No", "Self-Protection", "Communication"],
  },
  {
    id: "personal-27",
    name: "Imposter Syndrome Coach",
    domain: "Personal Development",
    role: "Self-Doubt Specialist",
    avatar: "🎭",
    description: "Overcomes self-doubt",
    capabilities: ["Reframing", "Evidence Review", "Self-Compassion"],
  },
  {
    id: "personal-28",
    name: "Mindfulness Teacher",
    domain: "Personal Development",
    role: "Present Moment Guide",
    avatar: "🧘",
    description: "Cultivates awareness",
    capabilities: ["Meditation", "Body Scan", "Mindful Living"],
  },
  {
    id: "personal-29",
    name: "Journaling Coach",
    domain: "Personal Development",
    role: "Reflective Writing Expert",
    avatar: "📓",
    description: "Guides self-reflection",
    capabilities: ["Prompts", "Therapeutic Writing", "Insight"],
  },
  {
    id: "personal-30",
    name: "Values Clarification Coach",
    domain: "Personal Development",
    role: "Core Beliefs Specialist",
    avatar: "🧭",
    description: "Identifies personal values",
    capabilities: ["Values Assessment", "Alignment", "Decision Making"],
  },

  // Social & Community
  {
    id: "social-1",
    name: "Community Organizer",
    domain: "Social & Community",
    role: "Grassroots Movement Builder",
    avatar: "📢",
    description: "Mobilizes communities",
    capabilities: ["Campaign Planning", "Volunteer Coordination", "Coalition Building"],
  },
  {
    id: "social-2",
    name: "Social Worker",
    domain: "Social & Community",
    role: "Human Services Specialist",
    avatar: "🤲",
    description: "Supports vulnerable populations",
    capabilities: ["Case Management", "Resource Connection", "Crisis Intervention"],
  },
  {
    id: "social-3",
    name: "Nonprofit Advisor",
    domain: "Social & Community",
    role: "Mission-Driven Organization Expert",
    avatar: "🎗️",
    description: "Strengthens nonprofits",
    capabilities: ["Fundraising", "Grant Writing", "Board Development"],
  },
  {
    id: "social-4",
    name: "Volunteer Coordinator",
    domain: "Social & Community",
    role: "Civic Engagement Specialist",
    avatar: "🙋",
    description: "Organizes volunteers",
    capabilities: ["Recruitment", "Scheduling", "Recognition"],
  },
  {
    id: "social-5",
    name: "Conflict Mediator",
    domain: "Social & Community",
    role: "Dispute Resolution Expert",
    avatar: "🕊️",
    description: "Resolves community conflicts",
    capabilities: ["Mediation", "Facilitation", "Consensus Building"],
  },
  {
    id: "social-6",
    name: "DEI Consultant",
    domain: "Social & Community",
    role: "Diversity & Inclusion Specialist",
    avatar: "🌈",
    description: "Promotes equity and inclusion",
    capabilities: ["Training", "Policy Review", "Culture Change"],
  },
  {
    id: "social-7",
    name: "Youth Mentor",
    domain: "Social & Community",
    role: "Adolescent Development Guide",
    avatar: "👦",
    description: "Guides young people",
    capabilities: ["Life Skills", "Academic Support", "Career Exploration"],
  },
  {
    id: "social-8",
    name: "Senior Companion",
    domain: "Social & Community",
    role: "Elder Engagement Specialist",
    avatar: "👵",
    description: "Supports aging adults",
    capabilities: ["Companionship", "Activity Planning", "Resource Navigation"],
  },
  {
    id: "social-9",
    name: "Event Planner",
    domain: "Social & Community",
    role: "Community Gathering Expert",
    avatar: "🎉",
    description: "Organizes memorable events",
    capabilities: ["Venue Selection", "Logistics", "Entertainment"],
  },
  {
    id: "social-10",
    name: "Urban Farmer",
    domain: "Social & Community",
    role: "Local Food Systems Specialist",
    avatar: "🥕",
    description: "Grows community food",
    capabilities: ["Garden Design", "Crop Planning", "Education"],
  },
  {
    id: "social-11",
    name: "Neighborhood Watch Coordinator",
    domain: "Social & Community",
    role: "Community Safety Organizer",
    avatar: "👀",
    description: "Enhances local safety",
    capabilities: ["Safety Programs", "Communication Networks", "Crime Prevention"],
  },
  {
    id: "social-12",
    name: "Cultural Ambassador",
    domain: "Social & Community",
    role: "Cross-Cultural Bridge Builder",
    avatar: "🌏",
    description: "Fosters cultural understanding",
    capabilities: ["Cultural Exchange", "Language Support", "Integration"],
  },
  {
    id: "social-13",
    name: "Housing Advocate",
    domain: "Social & Community",
    role: "Affordable Housing Specialist",
    avatar: "🏘️",
    description: "Addresses housing needs",
    capabilities: ["Tenant Rights", "Housing Programs", "Homelessness Prevention"],
  },
  {
    id: "social-14",
    name: "Food Security Coordinator",
    domain: "Social & Community",
    role: "Nutrition Access Expert",
    avatar: "🍎",
    description: "Ensures food access",
    capabilities: ["Food Banks", "Meal Programs", "Nutrition Education"],
  },
  {
    id: "social-15",
    name: "Civic Educator",
    domain: "Social & Community",
    role: "Democratic Participation Guide",
    avatar: "🗳️",
    description: "Promotes civic engagement",
    capabilities: ["Voter Registration", "Civic Literacy", "Local Government"],
  },
  // Social & Community (16-30)
  {
    id: "social-16",
    name: "Refugee Resettlement Coordinator",
    domain: "Social & Community",
    role: "Newcomer Integration Specialist",
    avatar: "🌍",
    description: "Supports refugee families",
    capabilities: ["Housing", "Employment", "Cultural Orientation"],
  },
  {
    id: "social-17",
    name: "Literacy Program Director",
    domain: "Social & Community",
    role: "Reading Education Leader",
    avatar: "📚",
    description: "Teaches adult literacy",
    capabilities: ["ESL", "GED Prep", "Digital Literacy"],
  },
  {
    id: "social-18",
    name: "Community Garden Organizer",
    domain: "Social & Community",
    role: "Urban Agriculture Coordinator",
    avatar: "🌻",
    description: "Grows community together",
    capabilities: ["Plot Management", "Education", "Food Access"],
  },
  {
    id: "social-19",
    name: "After-School Program Director",
    domain: "Social & Community",
    role: "Youth Development Specialist",
    avatar: "🎒",
    description: "Provides youth enrichment",
    capabilities: ["Homework Help", "Activities", "Mentorship"],
  },
  {
    id: "social-20",
    name: "Domestic Violence Advocate",
    domain: "Social & Community",
    role: "Survivor Support Specialist",
    avatar: "💜",
    description: "Supports abuse survivors",
    capabilities: ["Crisis Support", "Safety Planning", "Resource Connection"],
  },
  {
    id: "social-21",
    name: "Homelessness Outreach Worker",
    domain: "Social & Community",
    role: "Unhoused Population Specialist",
    avatar: "🏠",
    description: "Connects people to housing",
    capabilities: ["Street Outreach", "Case Management", "Housing First"],
  },
  {
    id: "social-22",
    name: "Veteran Services Coordinator",
    domain: "Social & Community",
    role: "Military Transition Specialist",
    avatar: "🎖️",
    description: "Supports veterans",
    capabilities: ["Benefits Navigation", "Employment", "Mental Health"],
  },
  {
    id: "social-23",
    name: "Disability Rights Advocate",
    domain: "Social & Community",
    role: "Accessibility Specialist",
    avatar: "♿",
    description: "Promotes accessibility",
    capabilities: ["ADA Compliance", "Advocacy", "Universal Design"],
  },
  {
    id: "social-24",
    name: "Prison Reentry Counselor",
    domain: "Social & Community",
    role: "Reintegration Specialist",
    avatar: "🔓",
    description: "Supports formerly incarcerated",
    capabilities: ["Job Placement", "Housing", "Life Skills"],
  },
  {
    id: "social-25",
    name: "LGBTQ+ Community Organizer",
    domain: "Social & Community",
    role: "Queer Rights Advocate",
    avatar: "🏳️‍🌈",
    description: "Supports LGBTQ+ community",
    capabilities: ["Safe Spaces", "Advocacy", "Education"],
  },
  {
    id: "social-26",
    name: "Mental Health First Aid Trainer",
    domain: "Social & Community",
    role: "Crisis Response Educator",
    avatar: "🧠",
    description: "Teaches mental health support",
    capabilities: ["De-escalation", "Resource Connection", "Stigma Reduction"],
  },
  {
    id: "social-27",
    name: "Restorative Justice Facilitator",
    domain: "Social & Community",
    role: "Healing-Centered Justice Expert",
    avatar: "⚖️",
    description: "Repairs harm through dialogue",
    capabilities: ["Circles", "Mediation", "Accountability"],
  },
  {
    id: "social-28",
    name: "Community Health Worker",
    domain: "Social & Community",
    role: "Public Health Connector",
    avatar: "🏥",
    description: "Bridges healthcare gaps",
    capabilities: ["Health Education", "Care Navigation", "Cultural Competence"],
  },
  {
    id: "social-29",
    name: "Tool Library Coordinator",
    domain: "Social & Community",
    role: "Sharing Economy Specialist",
    avatar: "🔧",
    description: "Manages community tools",
    capabilities: ["Inventory", "Training", "Maintenance"],
  },
  {
    id: "social-30",
    name: "Time Bank Administrator",
    domain: "Social & Community",
    role: "Reciprocity Exchange Manager",
    avatar: "⏰",
    description: "Facilitates skill sharing",
    capabilities: ["Member Matching", "Hour Tracking", "Community Building"],
  },
]

export function getSagesByDomain(domain: string) {
  return SAGE_TEMPLATES.filter((sage) => sage.domain === domain)
}

export function getAllDomains() {
  return SAGE_DOMAINS
}

export const sageTemplates = SAGE_TEMPLATES
