// Feature flags and cost guardrails for SageSpace

export const FEATURE_FLAGS = {
  // Artifact generation
  TEXT_GENERATION: true,
  AUDIO_GENERATION: process.env.ENABLE_AUDIO_GEN === "true",
  IMAGE_GENERATION: process.env.ENABLE_IMAGE_GEN === "true",
  VIDEO_GENERATION: process.env.ENABLE_VIDEO_GEN === "true",

  // Social features
  FEED_ENABLED: true,
  COMMENTS_ENABLED: true,
  REMIX_ENABLED: true,

  // Monetization
  CREDITS_SYSTEM: true,
  STRIPE_ENABLED: process.env.STRIPE_SECRET_KEY !== undefined,
  MARKETPLACE_ENABLED: false, // Coming soon

  // Safety
  PII_FILTERING: true,
  CONTENT_PROVENANCE: true,
  WATERMARKING: true,
  CITATION_REQUIRED: true,
}

export const RATE_LIMITS = {
  free: {
    artifacts_per_day: 10,
    threads_per_day: 20,
    messages_per_hour: 100,
    remixes_per_day: 5,
  },
  pro: {
    artifacts_per_day: 100,
    threads_per_day: 200,
    messages_per_hour: 500,
    remixes_per_day: 50,
  },
  team: {
    artifacts_per_day: 500,
    threads_per_day: 1000,
    messages_per_hour: 2000,
    remixes_per_day: 200,
  },
}

export const CREDIT_COSTS = {
  text_artifact: 1,
  audio_artifact: 5,
  image_artifact: 3,
  video_artifact: 10,
  remix: 2,
  circle_session: 5,
}

export const XP_REWARDS = {
  create_sage: 100,
  create_artifact: 10,
  remix_artifact: 15,
  share_to_feed: 50,
  validate_claim: 20,
  complete_quest: 100,
  daily_streak: 10,
  receive_like: 2,
  receive_remix: 5,
}

export const PLAN_PRICES = {
  pro_monthly: 999, // $9.99
  pro_annual: 9900, // $99/year (2 months free)
  team_monthly: 4999, // $49.99/month
  enterprise: "custom",
}

export const MODEL_PROVIDERS = {
  text: process.env.TEXT_MODEL || "groq/mixtral-8x7b-32768",
  audio: process.env.AUDIO_MODEL || "elevenlabs/eleven_monolingual_v1",
  image: process.env.IMAGE_MODEL || "stability-ai/sdxl",
  video: process.env.VIDEO_MODEL || "runway/gen-2",
}

export const SAFETY_CONFIG = {
  pii_patterns: [
    /\b\d{3}-\d{2}-\d{4}\b/g, // SSN
    /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, // Email
    /\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/g, // Phone
  ],
  watermark_text: "Generated by SageSpace AI",
  required_disclosures: ["This content was generated by AI", "Citations required for factual claims"],
}
